/* ─── AUREVIA SKIN — Journal / Blog Data ─── */

export interface BlogPost {
  slug: string;
  title: string;
  subtitle: string;
  category: string;
  tag: string;
  author: string;
  authorRole: string;
  publishedAt: string;
  readTime: string;
  image: string;
  excerpt: string;
  featured: boolean;
  content: BlogSection[];
  relatedSlugs: string[];
  seoTitle?: string;
  seoDescription?: string;
}

export interface BlogSection {
  type: "intro" | "h2" | "h3" | "p" | "quote" | "tip" | "list" | "divider" | "product-cta";
  text?: string;
  items?: string[];
  product?: string;
  productSlug?: string;
}

export const blogPosts: BlogPost[] = [
  /* ──────────────────────────────────────────────── */
  /* 1. Morning Routine                               */
  /* ──────────────────────────────────────────────── */
  {
    slug: "morning-skincare-routine",
    title: "The Perfect Morning Glow Routine",
    subtitle: "A step-by-step guide to starting your day with luminous, protected skin",
    category: "Routine",
    tag: "Routine",
    author: "Anika Sharma",
    authorRole: "Senior Skincare Formulator",
    publishedAt: "2026-07-10",
    readTime: "6 min read",
    image: "/images/journal-morning.png",
    featured: true,
    excerpt:
      "Your morning routine sets the tone for your skin's entire day. Get it right and your skin stays hydrated, protected and visibly radiant from sunrise to sundown.",
    relatedSlugs: ["science-hyaluronic-acid", "ceramides-barrier-repair"],
    seoTitle: "Perfect Morning Skincare Routine — AUREVIA SKIN",
    seoDescription:
      "Follow our step-by-step morning skincare routine for glowing, protected skin all day. Expert advice from AUREVIA SKIN.",
    content: [
      {
        type: "intro",
        text: "Your morning skincare routine is more than a ritual — it's the foundation of healthy, luminous skin. Done right, it prepares your skin to face UV exposure, pollution and stress while maintaining the hydration and barrier function you worked to build overnight.",
      },
      {
        type: "h2",
        text: "Why Morning Routine Matters",
      },
      {
        type: "p",
        text: "During the night, your skin undergoes regeneration and repair. By morning, it has produced new cells and increased transepidermal water loss (TEWL). A properly sequenced morning routine seals in that overnight work, defends against daytime aggressors, and sets a luminous base.",
      },
      {
        type: "quote",
        text: "The best skincare routine is one you actually do consistently. Start with 3 steps and add more only when you're ready.",
      },
      {
        type: "h2",
        text: "Step 1 — Cleanse",
      },
      {
        type: "p",
        text: "Begin with a gentle, pH-balanced cleanser. In the morning, your goal isn't to strip last night's skincare — it's to remove sweat, sebum that built up overnight, and any residue from your pillowcase. Use lukewarm water and a milky or gel cleanser that leaves skin feeling soft, never tight.",
      },
      {
        type: "tip",
        text: "If you have dry or normal skin, a quick water rinse is often enough in the morning — saving your full cleanse for the evening.",
      },
      {
        type: "h2",
        text: "Step 2 — Tone (Optional but Powerful)",
      },
      {
        type: "p",
        text: "A good toner balances your skin's pH after cleansing, preps the skin to absorb actives more efficiently, and can deliver a first hit of hydration. Look for toners with hyaluronic acid, niacinamide, or soothing botanicals — avoid anything with drying alcohol.",
      },
      {
        type: "h2",
        text: "Step 3 — Vitamin C Serum",
      },
      {
        type: "p",
        text: "Morning is the ideal time for Vitamin C. This antioxidant powerhouse neutralises free radicals generated by UV exposure and environmental pollution, boosts collagen synthesis, and brightens your complexion over time. Apply to dry skin and allow 60 seconds to absorb before the next step.",
      },
      {
        type: "product-cta",
        text: "Vitamin C Brightening Serum",
        productSlug: "vitamin-c-serum",
      },
      {
        type: "h2",
        text: "Step 4 — Moisturise",
      },
      {
        type: "p",
        text: "Lock in your serum and provide a protective hydration layer. In the morning, opt for a lightweight moisturiser that absorbs cleanly — avoiding heavy occlusive creams that can pill under SPF or makeup. Look for ceramides, peptides or hyaluronic acid.",
      },
      {
        type: "h2",
        text: "Step 5 — SPF (Non-Negotiable)",
      },
      {
        type: "p",
        text: "SPF is the single most evidence-backed anti-aging product in existence. UVA radiation (which penetrates glass) is responsible for up to 80% of visible skin aging. Apply SPF 30 minimum every single morning — even on cloudy days, even when working indoors near windows.",
      },
      {
        type: "list",
        items: [
          "Apply SPF as the very last skincare step, after moisturiser",
          "Use a quarter teaspoon for face and neck",
          "Reapply every 2 hours if outdoors",
          "Mineral SPFs are great for sensitive skin — they work immediately on application",
        ],
      },
      {
        type: "product-cta",
        text: "Mineral SPF 50 Sunscreen",
        productSlug: "mineral-spf50",
      },
      {
        type: "h2",
        text: "The Full Morning Sequence",
      },
      {
        type: "list",
        items: [
          "Cleanser — 60 seconds massage",
          "Toner (optional) — pat in gently",
          "Vitamin C serum — press into skin, wait 60 seconds",
          "Eye cream — tap with ring finger",
          "Moisturiser — massage in upward motions",
          "SPF 50 — apply generously, do not skip",
        ],
      },
      {
        type: "quote",
        text: "Skin that is consistently protected from UV damage ages significantly more slowly than unprotected skin. SPF is your most powerful anti-aging tool.",
      },
    ],
  },

  /* ──────────────────────────────────────────────── */
  /* 2. Hyaluronic Acid Science                       */
  /* ──────────────────────────────────────────────── */
  {
    slug: "science-hyaluronic-acid",
    title: "Understanding Skin Hydration",
    subtitle: "The science behind hyaluronic acid and why skin moisture is more complex than you think",
    category: "Science",
    tag: "Science",
    author: "Dr. Priya Mehta",
    authorRole: "Cosmetic Dermatologist",
    publishedAt: "2026-07-05",
    readTime: "8 min read",
    image: "/images/journal-hydration.png",
    featured: true,
    excerpt:
      "Hyaluronic acid holds up to 1000x its weight in water — but that's only half the story. Learn how skin hydration truly works and why the molecular weight of HA matters.",
    relatedSlugs: ["morning-skincare-routine", "ceramides-barrier-repair"],
    content: [
      {
        type: "intro",
        text: "Hyaluronic acid is one of the most researched, validated and beloved ingredients in skincare — but the way it's marketed often oversimplifies an extraordinarily elegant biological system. Let's go deeper.",
      },
      {
        type: "h2",
        text: "What Is Hyaluronic Acid?",
      },
      {
        type: "p",
        text: "Hyaluronic acid (HA) is a glycosaminoglycan — a long chain of sugars — naturally produced by your body and found in abundance in the skin, eyes and joints. In the dermis alone, HA makes up roughly 50% of the body's total HA content, where it forms a hydrated gel that gives skin its volume, plumpness and resilience.",
      },
      {
        type: "p",
        text: "The famous claim that HA holds 1000x its weight in water is technically accurate — in a lab setting. In skin, the actual hydration delivered depends heavily on the molecular weight of the HA molecule used.",
      },
      {
        type: "h2",
        text: "Why Molecular Weight Is Everything",
      },
      {
        type: "p",
        text: "Hyaluronic acid molecules come in different sizes — measured in Daltons (Da). This size determines where in the skin the molecule can reach:",
      },
      {
        type: "list",
        items: [
          "High molecular weight HA (>1000 kDa) — sits on the surface, forms a film, reduces TEWL, gives immediate plumping effect",
          "Medium molecular weight HA (100–1000 kDa) — penetrates the upper layers of the epidermis for deeper surface hydration",
          "Low molecular weight HA (<10 kDa) — penetrates more deeply, reaches the dermis, stimulates fibroblasts and HA production",
          "Sodium Hyaluronate — the salt form, smaller and more stable, penetrates more effectively than free HA",
        ],
      },
      {
        type: "tip",
        text: "Always look for serums that contain multiple molecular weights of HA — this 'multi-depth' approach hydrates at every layer of the skin simultaneously.",
      },
      {
        type: "h2",
        text: "The Humectant Trap",
      },
      {
        type: "p",
        text: "Here's something most brands won't tell you: in dry climates or during winter, humectants like HA can actually draw moisture out of the deeper skin layers when the air has less than 70% relative humidity — potentially leaving skin more dehydrated than before. This is why applying HA to damp skin (not dry) and always sealing it with a moisturiser is non-negotiable.",
      },
      {
        type: "quote",
        text: "Hyaluronic acid is like a sponge — extraordinary at holding water, but it needs water to work with. Apply to damp skin, always seal with a moisturiser.",
      },
      {
        type: "h2",
        text: "Signs Your Skin Is Dehydrated (Not Just Dry)",
      },
      {
        type: "p",
        text: "Dehydration and dryness are often confused. Dry skin is a skin type — lacking oil. Dehydration is a skin condition — lacking water — that can affect any skin type including oily skin.",
      },
      {
        type: "list",
        items: [
          "Skin feels tight and looks dull despite being oily",
          "Fine lines appear more pronounced than usual",
          "Skin doesn't 'bounce back' when you pinch it gently",
          "Foundation looks cakey or separates quickly",
          "Skin feels rough but isn't flaky or dry to the touch",
        ],
      },
      {
        type: "product-cta",
        text: "Radiance Serum — Triple-Weight HA Formula",
        productSlug: "radiance-serum",
      },
      {
        type: "h2",
        text: "The Hydration Protocol",
      },
      {
        type: "list",
        items: [
          "Apply your HA serum to slightly damp skin (after toning or misting)",
          "Immediately follow with a moisturiser to seal",
          "Add an occlusive (facial oil or balm) in very dry conditions",
          "Drink adequate water — internal hydration matters too",
          "Use a humidifier in air-conditioned rooms",
        ],
      },
    ],
  },

  /* ──────────────────────────────────────────────── */
  /* 3. Ceramides & Barrier Repair                    */
  /* ──────────────────────────────────────────────── */
  {
    slug: "ceramides-barrier-repair",
    title: "Building Your Skin Barrier",
    subtitle: "Why ceramides are the most underrated ingredient in skincare — and how to repair a compromised barrier",
    category: "Education",
    tag: "Education",
    author: "Anika Sharma",
    authorRole: "Senior Skincare Formulator",
    publishedAt: "2026-07-01",
    readTime: "7 min read",
    image: "/images/journal-barrier.png",
    featured: false,
    excerpt:
      "Your skin barrier — the stratum corneum — is your body's primary line of defence against the world. When it's compromised, everything from sensitivity to acne to premature aging can result.",
    relatedSlugs: ["science-hyaluronic-acid", "clean-beauty-philosophy"],
    content: [
      {
        type: "intro",
        text: "The skin barrier is having its long-overdue moment in skincare. But despite the buzz, most people still don't understand what it is, what damages it, and — critically — how to repair it. Let's break it down.",
      },
      {
        type: "h2",
        text: "What Is the Skin Barrier?",
      },
      {
        type: "p",
        text: "The skin barrier, technically called the stratum corneum, is the outermost layer of skin — a complex structure of corneocytes (dead skin cells) embedded in a lipid matrix. Scientists famously describe it as 'bricks and mortar': the cells are the bricks, and the lipids — primarily ceramides, cholesterol and fatty acids — are the mortar that holds everything together.",
      },
      {
        type: "p",
        text: "This barrier has two primary jobs: keeping moisture in, and keeping harmful substances out (allergens, pollution, bacteria). When it's healthy, skin feels soft, plump and calm. When it's compromised — the mortar has cracked — everything goes wrong.",
      },
      {
        type: "h2",
        text: "Signs of a Compromised Barrier",
      },
      {
        type: "list",
        items: [
          "Persistent redness or blotchy skin",
          "Skin feels tight, rough or flaky",
          "Products that used to work suddenly sting or burn",
          "Increased sensitivity to temperature and touch",
          "Breakouts that don't respond to usual treatments",
          "Skin that never feels truly hydrated despite heavy moisturisers",
        ],
      },
      {
        type: "h2",
        text: "What Damages the Barrier?",
      },
      {
        type: "p",
        text: "Ironically, many skincare habits we think are beneficial are actually damaging the barrier over time:",
      },
      {
        type: "list",
        items: [
          "Over-exfoliating — using acids or scrubs too frequently",
          "Harsh foaming cleansers with SLS that strip natural lipids",
          "Using retinol at too high a concentration too quickly",
          "Hot water — dissolves the lipid layer",
          "Environmental stressors — UV exposure, pollution, extreme cold",
          "Fragrance in skincare — a leading cause of sensitisation",
        ],
      },
      {
        type: "quote",
        text: "The most important skincare step is often the one you stop doing — over-cleansing, over-exfoliating, layering too many actives.",
      },
      {
        type: "h2",
        text: "Enter Ceramides",
      },
      {
        type: "p",
        text: "Ceramides make up approximately 50% of the lipid composition of the stratum corneum. As we age — and especially after barrier disruption — ceramide levels naturally decline, leading to the characteristic dryness, sensitivity and fine lines of mature skin.",
      },
      {
        type: "p",
        text: "The most effective ceramide formulas use ceramides in the correct physiological ratio: roughly 1:2:1 of ceramides:cholesterol:fatty acids. This mirrors the exact lipid profile of healthy human skin and is far more effective than ceramides used in isolation.",
      },
      {
        type: "tip",
        text: "Look for formulas listing ceramide NP, ceramide AP AND ceramide EOP together. These three work synergistically — individually, their effect is significantly weaker.",
      },
      {
        type: "product-cta",
        text: "Ceramide Repair Cream",
        productSlug: "ceramide-repair-cream",
      },
      {
        type: "h2",
        text: "The Barrier Repair Protocol",
      },
      {
        type: "list",
        items: [
          "Simplify your routine — strip back to cleanser, moisturiser, SPF",
          "Pause all actives (acids, retinol, vitamin C) for 1–2 weeks",
          "Switch to a gentle, pH-balanced, fragrance-free cleanser",
          "Use a ceramide-rich moisturiser twice daily",
          "Avoid hot showers — lukewarm only",
          "Re-introduce one active at a time after 2 weeks",
        ],
      },
    ],
  },

  /* ──────────────────────────────────────────────── */
  /* 4. Night Recovery Ritual                         */
  /* ──────────────────────────────────────────────── */
  {
    slug: "night-recovery-ritual",
    title: "The Night Recovery Ritual",
    subtitle: "How to maximise your skin's natural overnight repair cycle with the right products and techniques",
    category: "Ritual",
    tag: "Ritual",
    author: "Dr. Priya Mehta",
    authorRole: "Cosmetic Dermatologist",
    publishedAt: "2026-06-28",
    readTime: "5 min read",
    image: "/images/journal-night.png",
    featured: true,
    excerpt:
      "Between 11pm and 4am, your skin's repair mechanisms peak. This is when cell turnover accelerates, collagen production increases, and your skincare works hardest. Here's how to take full advantage.",
    relatedSlugs: ["ceramides-barrier-repair", "morning-skincare-routine"],
    content: [
      {
        type: "intro",
        text: "Your skin operates on a circadian rhythm. During the day, it's in defence mode — neutralising free radicals, protecting against UV, managing moisture loss. At night, the biological dial switches to repair and renewal. Understanding this shift changes how you approach your evening routine.",
      },
      {
        type: "h2",
        text: "The Skin's Circadian Clock",
      },
      {
        type: "p",
        text: "Research shows that between 11pm and 4am, skin cells divide up to 8 times faster than during the day. Collagen synthesis is elevated. Melatonin — produced during sleep — is a potent antioxidant that protects skin cells from oxidative damage. Blood flow to the skin increases, delivering nutrients and removing waste products.",
      },
      {
        type: "p",
        text: "Simultaneously, skin temperature rises slightly at night, increasing product penetration. Your carefully applied actives are absorbed more deeply and work more efficiently than the same products applied in the morning.",
      },
      {
        type: "quote",
        text: "Night is when you invest in your skin's future. The products you apply while you sleep have 7–8 hours of uninterrupted time to work.",
      },
      {
        type: "h2",
        text: "Step 1 — Double Cleanse",
      },
      {
        type: "p",
        text: "Evening cleansing is more thorough than morning. Start with an oil-based cleanser or micellar water to dissolve sunscreen, makeup and sebum — these cannot be fully removed by water-based cleansers alone. Follow with your gentle foam cleanser for a clean slate.",
      },
      {
        type: "h2",
        text: "Step 2 — Toner",
      },
      {
        type: "p",
        text: "After cleansing, apply your toner while the skin is still slightly damp. This restores pH balance and prepares skin to receive actives. A niacinamide toner is particularly effective in the evening — this ingredient visibly minimises pores and reduces oiliness overnight.",
      },
      {
        type: "h2",
        text: "Step 3 — Retinol (2–3 Nights Per Week)",
      },
      {
        type: "p",
        text: "Retinol is a night-only ingredient — it degrades in UV light and can cause photosensitisation. Apply a pea-sized amount to fully dry skin 20 minutes after toning. Encapsulated retinol formulas release the active gradually, dramatically reducing the purging and irritation associated with traditional retinol.",
      },
      {
        type: "tip",
        text: "The 'sandwich method' for retinol beginners: apply a thin layer of moisturiser, then retinol, then moisturiser again. This buffers the retinol and reduces irritation while maintaining efficacy.",
      },
      {
        type: "product-cta",
        text: "Retinol Renewal Serum",
        productSlug: "retinol-renewal-serum",
      },
      {
        type: "h2",
        text: "Step 4 — Facial Oil",
      },
      {
        type: "p",
        text: "Night is the ideal time for facial oils. Richer and more nourishing than daytime options, oils like rosehip and bakuchiol work overnight to deliver essential fatty acids, fat-soluble vitamins, and plant antioxidants deep into the skin. Apply 3–4 drops after your serum, pressing gently into skin.",
      },
      {
        type: "product-cta",
        text: "Night Recovery Oil",
        productSlug: "night-oil",
      },
      {
        type: "h2",
        text: "Step 5 — Sleeping Mask (2–3 Nights Per Week)",
      },
      {
        type: "p",
        text: "A leave-on sleeping mask applied as your final step creates an occlusive seal that prevents overnight moisture loss. The best formulas combine humectants (HA), emollients (ceramides, fatty acids) and occlusives — trapping moisture and actives against the skin for 8 hours of concentrated treatment.",
      },
      {
        type: "h2",
        text: "The Pillow Rule",
      },
      {
        type: "list",
        items: [
          "Silk pillowcases cause less friction — reducing fine lines and hair breakage",
          "Change your pillowcase every 2–3 days — cotton absorbs sebum and bacteria",
          "Sleep on your back when possible — side sleeping causes 'sleep wrinkles' over time",
          "Elevate your head slightly — reduces morning puffiness by preventing fluid pooling",
        ],
      },
    ],
  },

  /* ──────────────────────────────────────────────── */
  /* 5. Clean Beauty Philosophy                       */
  /* ──────────────────────────────────────────────── */
  {
    slug: "clean-beauty-philosophy",
    title: "Why We Never Use Parabens or Sulfates",
    subtitle: "Our ingredient philosophy, what we exclude and why — and what we use instead",
    category: "Philosophy",
    tag: "Philosophy",
    author: "Riya Desai",
    authorRole: "Head of Formulation",
    publishedAt: "2026-06-20",
    readTime: "5 min read",
    image: "/images/ingredients.png",
    featured: false,
    excerpt:
      "Clean beauty means different things to different brands. Here's exactly what AUREVIA SKIN excludes from our formulas, the science behind each decision, and the powerful alternatives we use instead.",
    relatedSlugs: ["ceramides-barrier-repair", "science-hyaluronic-acid"],
    content: [
      {
        type: "intro",
        text: "The term 'clean beauty' is used so broadly it has almost lost meaning. At AUREVIA SKIN, our approach is simple: we exclude ingredients where strong scientific evidence suggests risk, and we never exclude ingredients simply because of popular misconception. Here's our actual list — and the reasoning behind it.",
      },
      {
        type: "h2",
        text: "What We Exclude — and Why",
      },
      {
        type: "h3",
        text: "Sulphates (SLS, SLES)",
      },
      {
        type: "p",
        text: "Sodium Lauryl Sulphate is an extremely effective surfactant — so effective that it strips not just dirt but also the natural lipids that make up your skin barrier. Repeated use causes measurable barrier disruption and increases TEWL. We use amino acid-derived surfactants instead, which clean effectively at skin-friendly pH without disturbing the lipid matrix.",
      },
      {
        type: "h3",
        text: "Parabens",
      },
      {
        type: "p",
        text: "Parabens are preservatives with a strong safety record. However, they are xenoestrogens — compounds that weakly mimic estrogen — and while the risk from topical application is considered low by most regulatory bodies, we choose to use alternative preservation systems (phenoxyethanol combined with ethylhexylglycerin) that are equally effective without the theoretical concern.",
      },
      {
        type: "h3",
        text: "Synthetic Fragrance",
      },
      {
        type: "p",
        text: "Fragrance is the number-one cause of cosmetic contact sensitisation. Synthetic fragrance blends can contain dozens of undisclosed chemical compounds under a single label term. We use only skin-safe, naturally derived aromatic extracts at concentrations below sensitisation thresholds — and we always disclose every ingredient.",
      },
      {
        type: "h3",
        text: "Mineral Oil",
      },
      {
        type: "p",
        text: "Mineral oil is actually a highly refined, safe ingredient. We exclude it not for safety reasons but for efficacy — it sits on the skin surface as a pure occlusive without delivering any additional bioactive benefit. We prefer plant-derived squalane, which is biocompatible with skin's own sebum and provides excellent occlusion plus additional antioxidant activity.",
      },
      {
        type: "quote",
        text: "Every ingredient we use is there for a reason. Every ingredient we exclude has a documented reason for exclusion. We never exclude based on trends.",
      },
      {
        type: "h2",
        text: "What We Use Instead",
      },
      {
        type: "list",
        items: [
          "Amino acid surfactants — gentle cleansing at correct skin pH",
          "Phenoxyethanol + Ethylhexylglycerin — broad-spectrum preservation without parabens",
          "Plant squalane (from sugarcane) — biocompatible occlusion and antioxidant",
          "Ceramide complexes — genuine barrier repair, not just surface comfort",
          "Bakuchiol — clinically comparable to retinol without irritation",
          "Ethyl ascorbic acid — the most stable, effective form of Vitamin C",
        ],
      },
      {
        type: "h2",
        text: "Our Certification Standards",
      },
      {
        type: "p",
        text: "All AUREVIA SKIN products are formulated to comply with EU Cosmetics Regulation — the strictest in the world. We are cruelty-free, never testing on animals. Our packaging uses recycled and recyclable materials wherever technically possible without compromising product stability.",
      },
    ],
  },
];

/* ── Helpers ── */
export function getPostBySlug(slug: string): BlogPost | undefined {
  return blogPosts.find((p) => p.slug === slug);
}

export function getFeaturedPosts(): BlogPost[] {
  return blogPosts.filter((p) => p.featured);
}

export function getPostsByCategory(category: string): BlogPost[] {
  return blogPosts.filter((p) => p.category === category);
}

export function getRelatedPosts(slug: string): BlogPost[] {
  const post = getPostBySlug(slug);
  if (!post) return [];
  return post.relatedSlugs
    .map((s) => getPostBySlug(s))
    .filter((p): p is BlogPost => p !== undefined);
}

export function formatDate(iso: string): string {
  return new Date(iso).toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}
